commitizen:
  bump_message: '[skip ci] Bumping release version $current_version → $new_version'
  name: cz.conventional_commits
  tag_format: v$version
  update_changelog_on_bump: true
  version: 0.36.1
  version_files:
    - VERSION
  version_scheme: semver
