name: shared-deploy
author: Reece.fensome
description: shared-deploy
inputs:
  test:
    description: 'Test'
    required: true
runs:
  using: "composite"
  steps:
    - run: echo ${{ inputs.test }}
      shell: bash
