name: shared-deploy
author: Reece.fensome
description: shared-deploy
inputs:
  terraform_version:
    description: 'Test'
    required: false
    default: 1.7.5
  environment_name:
    description: 'Test'
    required: false
    default: 'dev'
  working_directory:
    description: 'Test'
    required: false
    default: 'platform'
runs:
  using: "composite"
  steps:
    - id: 'setup_terraform'
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ inputs.terraform_version }}

    - id: 'tf_init'
      run: terraform init --backend-config=./environments/${{ inputs.environment_name }}/terraform.backend
      shell: bash
      working-directory: ${{ inputs.working_directory }}

    - id: 'tf_validate'
      run: terraform validate
      shell: bash
      working-directory: ${{ inputs.working_directory }}
