# .github/workflows/crj-deploy.yml
name: Deploying Cloud Run Job

on:
  workflow_call:
    inputs:
      pipeline-name:
        required: true
        type: string
        description: The pipeline being deployed
      environment-name:
        required: true
        type: string
        description: The environment name being deployed to
      image-url:
        required: true
        type: string

permissions:
  contents: 'read'
  id-token: 'write'

run-name: ${{ github.actor }} has trigger deployment for ${{ inputs.pipeline-name }}  🚀

jobs:
  deploy-dev:
    if: ${{ inputs.environment-name == 'dev' }}
    environment: dev
    name: Deploy ${{ inputs.pipeline-name }} to ${{ inputs.environment-name }}
    runs-on: ubuntu-latest

    steps:
      - run: |
          echo "Running With Params"
          echo ${{ inputs.pipeline-name }}
          echo ${{ inputs.environment-name }}
          echo ${{ inputs.image-url }}

      - name: Checkout
        uses: actions/checkout@v4
#
#      - name: Authenticate to Google Cloud
#        uses: google-github-actions/auth@v2
#        with:
#          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
#          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
#
#      - name: Run Terraform
#        uses: ./.github/actions/tf-cli
#        with:
#          environment_name: ${{ inputs.environment-name }}
#          working_directory: 'pipelines/${{ inputs.pipeline-name }}'
#
#  deploy-test:
#    if: ${{ inputs.environment-name == 'test' }}
#    environment: dev
#    name: Deploy ${{ inputs.pipeline-name }} to ${{ inputs.environment-name }}
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v4
#
#      - name: Authenticate to Google Cloud
#        uses: google-github-actions/auth@v2
#        with:
#          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
#          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
#
#      - name: Run Terraform
#        uses: ./.github/actions/tf-cli
#        with:
#          environment_name: ${{ inputs.environment-name }}
#          working_directory: 'pipelines/${{ inputs.pipeline-name }}'
#
#  deploy-prod:
#    if: ${{ inputs.environment-name == 'prod' }}
#    environment: dev
#    name: Deploy ${{ inputs.pipeline-name }} to ${{ inputs.environment-name }}
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v4
#
#      - name: Authenticate to Google Cloud
#        uses: google-github-actions/auth@v2
#        with:
#          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
#          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
#
#      - name: Run Terraform
#        uses: ./.github/actions/tf-cli
#        with:
#          environment_name: ${{ inputs.environment-name }}
#          working_directory: 'pipelines/${{ inputs.pipeline-name }}'
#
#
#
#
#
