# .github/workflows/crj-deploy.yml
name: Deploying Cloud Run Job

on:
  workflow_dispatch:
    inputs:
      pipeline_name:
        required: true
        type: string
        description: The pipeline being deployed
      branch_name:
        required: true
        type: string
        description: The branch_name name being deployed to
      image_tag:
        required: true
        type: string
        description: The image tag to deployed

permissions:
  contents: 'read'
  id-token: 'write'

run-name: ${{ github.actor }} has trigger deployment for ${{ inputs.pipeline_name }}  🚀

jobs:
  deploy-dev:
    if: ${{  startsWith(inputs.branch_name, 'feature/') || inputs.branch_name == 'dev' }}
    environment: dev
    name: Deploy ${{ inputs.pipeline_name }} to ${{ inputs.environment_name }}
    runs-on: ubuntu-latest

    steps:
      - run: |
          echo "Running With Params"
          echo ${{ inputs.pipeline_name }}
          echo ${{ inputs.environment_name }}
          echo ${{ inputs.image_tag }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Run Terraform
        uses: ./.github/actions/tf-cli
        with:
          environment_name: dev
          working_directory: 'pipelines/${{ inputs.pipeline_name }}'
          run_apply: ${{ inputs.environment_name == 'dev' }}
