# .github/workflows/deploy.yml
name: Deploy

on:
  push:
    branches:
      - "feature/**"

jobs:
  deploy-dev:
    name: Application - Deploy to Dev
    uses: ./.github/workflows/tf_deploy.yml
    with:
      environment: dev






