# .github/workflows/deploy.yml
name: Deploy

on:
  push:
    branches:
      - "feature/**"

jobs:
  plan-dev:
    environment: dev
    uses: ./.github/workflows/tf_plan.yml
    secrets: inherit
    permissions:
      contents: read
      id-token: write

