# .github/workflows/platform-deploy.yml
name: Deploy Platform Change

on:
  pull_request:
    paths:
      - 'platform/**'
  push:
    branches:
      - 'main'
      - 'feature/**'
      - 'release/**'

permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  deploy-dev:
    environment: dev
    name: TF Deploy DEV
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Setup Terraform
        uses: ./.github/actions/tf-cli
        with:
          environment_name: dev
          working_directory: 'platform'





