name: platform-changes.yml
on:
  pull_request:
    paths:
      - 'platform/**'
  push:
    branches:
      - 'main'
      - 'feature/**'

jobs:
  tf_apply:
    environment: ${{ vars.ENVIRONMENT_NAME }}
    permissions:
      contents: 'read'
      id-token: 'write'
    uses: './.github/workflows/tf-deploy.yml@main'
    with:
      environment: ${{ vars.ENVIRONMENT_NAME }}
      working-directory: 'platform'
    secrets:
      workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
      gcp_service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

