name: Platform Workflow
on:
  pull_request:
    paths:
      - 'platform/**'
  push:
    branches:
      - 'main'
      - 'feature/**'

jobs:

  platform_deploy_dev:

    permissions:
      contents: 'read'
      id-token: 'write'

    name: Platform Deploy Dev
    uses: ./.github/workflows/deploy.yml
    with:
      environment: dev


