name: Platform Change
on:
  pull_request:
    paths:
      - 'platform/**'
  push:
    branches:
      - 'main'
      - 'feature/**'

jobs:
  auth:

    environment: dev

    runs-on: ubuntu-latest
    timeout-minutes: 10

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - id: 'auth'
        uses: .github/workflows/tf-deploy.yml
        with:
          environment: ${{ vars.ENVIRONMENT_NAME }}
          work_directory: 'platform'
        secrets: inherit
