name: Reusable Terraform Plan

on:
  workflow_call:
    inputs:
      working-directory:
        description: 'The directory where terraform commands will be run'
        required: false
        type: string
        default: './'
      environment:
        description: 'The directory where terraform commands will be run'
        required: true
        type: string
#    secrets:
      # These secrets are expected to be passed from the caller,
      # often inherited from an environment's secrets.
#      workload_identity_provider:
#        description: 'The GCP Workload Identity Provider'
#        required: true
#      service_account:
#        description: 'The GCP Service Account to impersonate'
#        required: true

jobs:
  terraform-plan:
    name: 'Terraform Plan'
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: 'Authenticate to GCP'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: terraform plan -input=false -no-color
