name: tf_plan.yml
on:
  workflow_call:

jobs:
  plan:
    environment: dev
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: test
        id: test
        shell: bash
        run: |
          echo "${{ secrets.GCP_SERVICE_ACCOUNT }}"
